# -*- coding: utf-8 -*-
"""labsheet_01_task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cOMvBztySZamHMDVCZMrHDsmhdha7fa

## Labsheet 01 - IT21170966

#### Task 2 - Question 1
"""

import pandas as pd

df = pd.read_csv('/content/Au_nanoparticle_dataset.csv', index_col=0, encoding='latin')

"""#### Task 2 - Question 2"""

# Filter the DataFrame to keep only the specified columns
filtered_df = df[['N_total', 'N_bulk', 'N_surface', 'R_avg']]

"""#### Task 2 - Question 3"""

# Display the first 20 samples
print(filtered_df.head(20))

"""#### Task 2 - Question 4"""

# Calculate mean, standard deviation, and quartiles
mean_values = filtered_df.mean()
std_values = filtered_df.std()
quartiles = filtered_df.quantile([0.25, 0.5, 0.75])

print("Mean values:\n", mean_values)
print("Standard deviation values:\n", std_values)
print("Quartile values:\n", quartiles)

"""#### Task 2 - Question 5"""

import matplotlib.pyplot as plt

# Plot histograms for each feature
fig, axs = plt.subplots(1, 4, figsize=(20, 5))

features = ['N_total', 'N_bulk', 'N_surface', 'R_avg']
for i, feature in enumerate(features):
    axs[i].hist(filtered_df[feature], bins=20)
    axs[i].set_title(feature)

plt.tight_layout()
plt.show()

"""#### Task 2 - Question 6"""

import seaborn as sns

# Create a PairGrid with histograms and KDE plots
g = sns.PairGrid(filtered_df)
g.map_upper(sns.histplot)  # Bivariate histogram
g.map_diag(sns.histplot, kde=True)  # Histogram with KDE on diagonal
g.map_lower(sns.kdeplot)  # Bivariate KDE plot

plt.show()